[package]
name = "Steve-Army"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
log = "0.4.28"
simplelog = "0.12.2"
clap = { version = "4.5.51", features = ["derive"] }
serde_json = "1.0.145"